name: Build Image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    container:
      image: quay.io/centos-bootc/bootc-image-builder:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: |
          rpm-ostree compose image --format=ociarchive \
          --initialize centos-bootc.yaml dest.oci-archive
